improve file detection logic

diff --git a/Dockerfile.centos b/Dockerfile.centos
--- a/Dockerfile.centos
+++ b/Dockerfile.centos
@@ -20,7 +20,7 @@ ARG CERT_KEY_NAME=key.pem
 ARG CERT_FILE_NAME=cert.pem
 ARG APP_ROOT_DIR=$DEPLOYMENT_DIR/WSC
 ARG APP_SERVER_DIR=/opt/WebSpellChecker/AppServer
-ARG APP_NAME_MASK=wsc_app*
+ARG APP_NAME_MASK=wsc_app*tar.gz
 ARG USER_NAME=wsc
 ARG SERVICE_FILES_DIR=/var/lib
 ARG USER_ID=2000
@@ -108,14 +108,17 @@ RUN yum update -y --skip-broken && \
 
 RUN groupadd --gid ${GROUP_ID} $USER_NAME && useradd --no-log-init --uid ${USER_ID} --gid ${GROUP_ID} $USER_NAME
 
-RUN	mkdir -p $CUSTOM_DICTIONARIES_DIR \
+RUN mkdir -p $CUSTOM_DICTIONARIES_DIR \
              $USER_DICTIONARIES_DIR \
              $SERVICE_FILES_DIR/WebSpellChecker \
              $APP_SERVER_DIR \
              /var/run/nginx
 
 COPY $FILES_DIR/$APP_NAME_MASK $DEPLOYMENT_DIR/
-RUN tar -xvf $DEPLOYMENT_DIR/$APP_NAME_MASK -C $DEPLOYMENT_DIR/ && \
+RUN PACKAGE_FILE=$(ls -1t $DEPLOYMENT_DIR/$APP_NAME_MASK 2>/dev/null | head -n 1) && \
+    [ -z "$PACKAGE_FILE" ] && echo "Error. Docker image build failed: No valid application package detected." && exit 1 || \
+    echo "Using package file: $PACKAGE_FILE" && \
+    tar -xvf $PACKAGE_FILE -C $DEPLOYMENT_DIR/ && \
     perl $APP_ROOT_DIR*/automated_install.pl && \
     rm -rf $APP_ROOT_DIR* $DEPLOYMENT_DIR/$APP_NAME_MASK && \
     [ -d "${APP_SERVER_DIR}/Logs" ] && tar -czvf "${APP_SERVER_DIR}"/Logs/img_build_logs.tar.gz ${APP_SERVER_DIR}/Logs/* --remove-files || \
@@ -125,7 +128,7 @@ RUN tar -xvf $DEPLOYMENT_DIR/$APP_NAME_MASK -C $DEPLOYMENT_DIR/ && \
     ln -s /dev/stdout $APP_SERVER_DIR/Logs/Child-1.log && \
     ln -s /dev/stdout $APP_SERVER_DIR/Logs/Action.log && \
     chown -R ${USER_ID}:${GROUP_ID} $SERVICE_FILES_DIR/WebSpellChecker $DICTIONARIES_DIR $APP_SERVER_DIR
-	
+
 COPY $FILES_DIR/certificate/$CERT_KEY_NAME $CERT_DIR/$CERT_KEY_NAME
 COPY $FILES_DIR/certificate/$CERT_FILE_NAME $CERT_DIR/$CERT_FILE_NAME
 COPY $FILES_DIR/configure* $APP_SERVER_DIR/
